import Vue from 'vue'
import {
  // Base,
  // Affix,
  // Anchor,
  // AutoComplete,
  // Alert,
  Avatar,
  // BackTop,
  // Badge,
  // Breadcrumb,
  Button,
  // Calendar,
  // Card,
  // Collapse,
  // Carousel,
  // Cascader,
  // Checkbox,
  Col,
  // DatePicker,
  // Divider,
  // Dropdown,
  // Form,
  // Icon,
  // Input,
  // InputNumber,
  // Layout,
  List,
  // LocaleProvider,
  // Menu,
  // Modal,
  // Pagination,
  // Popconfirm,
  // Popover,
  // Progress,
  // Radio,
  // Rate,
  Row,
  // Select,
  // Slider,
  // Spin,
  // Steps,
  // Switch,
  // Table,
  // Transfer,
  // Tree,
  // TreeSelect,
  // Tabs,
  // Tag,
  // TimePicker,
  // Timeline,
  // Tooltip,
  // Upload,
  // Drawer,
  // Skeleton,
  // Comment,
  // ConfigProvider,
} from "ant-design-vue";


Vue.component('a-button', Button);
Vue.component('a-row', Row);
Vue.component('a-col', Col);
Vue.component('a-avatar', Avatar);
Vue.component('a-list', List);
